eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8181/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    ribbon:
      path: /ribbon/**
      serviceId: service-ribbon
    feign:
      path: /feign/**
      serviceId: service-feign
    auth:
      path: /auth/**
      serviceId: auth-server