server:
  port: 8762

spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8181/eureka/
    instance:
        instance-id: microservicecloud-8762
        prefer-ip-address: true     #访问路径可以显示IP地址